version: '3'

name: freestyle-app
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: freestyle-app
    ports:
      - '5432:5432'